spring.application.name=MechDeck

spring.datasource.url=jdbc:postgresql://ep-muddy-leaf-a1yvtqxt-pooler.ap-southeast-1.aws.neon.tech:5432/MechDeck?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_fK2cwvbo5XzY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=9f4a1c7d6e2b8a0f3c5d9e1b7a4c6f2d8e0a3b5c7d9f1a2e4c6b8d0f3a5e7c1
jwt.expiration-ms=86400000
